version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    command: npm run start:dev

volumes:
  node_modules: